# Generated by Django 4.1.4 on 2022-12-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
