# Generated by Django 4.1.4 on 2022-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_usercart_usercartproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercartproduct",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
